### ISSUE TITLE
Unable to play library

### ISSUE THREAD

**Issue by izharzabri** [Jalle19/xbmc-video-server#223]
Hi Steve,

I'm unable to play movie this error appear. Please advice.

HTTP load failed with status 404. Load of media resource http://stream.nomadonline.net/xbmc-vfs/%2fmedia%2fpsa01%2fEIVOM1%2fMovies%2f47%20Ronin%20(2013)%20%5b1080p%5d%2f47.Ronin.2013.1080p.BluRay.x264.YIFY.mp4 failed. watchInBrowser
All candidate resources failed to load. Media load paused.

If i click on download it gives me this error
File not found
Firefox can't find the file at http://stream.nomadonline.net/xbmc-vfs//media/psa01/EIVOM1/Movies/47 Ronin (2013) [1080p]/47.Ronin.2013.1080p.BluRay.x264.YIFY.mp4.
    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.

FYI the files is there but not sure why it cannot find it.

**Comment by izharzabri** [comment]
Hi,

Its ok i've resolved the issue of 404 but now different error appear "no video with supported format and MIME type found" .

**Comment by Jalle19** [comment]
"no video with supported format and MIME type found" means your browser can't play the file. The application enables in-browser playback for certain files which Chrome can handle, but not Firefox. Use Chrome instead of you want to use the browser player, for other browsers you'll have to grab the playlist file and play that with VLC.
