### ISSUE TITLE
Cannot create initial database

### ISSUE THREAD

**Issue by godfuture** [Jalle19/xbmc-video-server#225]
I initially tried to setup xbmc-video-server and stuck at creating the schema in mysql. Closely every step in readme seemed to work:
```
sudo su 
apt-get install libapache2-mod-php5 php5-gd php5-cli php5-sqlite php5-json php5-gd git curl
a2enmod rewrite expires
service apache2 restart
cd /var/www/html
git clone git://github.com/Jalle19/xbmc-video-server.git
cd xbmc-video-server
curl -sS https://getcomposer.org/installer | php
php composer.phar install
```
but the next one (initial database creation)
```
./src/protected/yiic createinitialdatabase
```
fails in unknown command error
```
myuser@myserver:/var/www/xbmc-video-server$ sudo ./src/protected/yiic createinitialdatabase
```
I suspected file permissions and changed it from apache user to root. I have used the full path instead of from current dir.

What could be the reason?

OS: ubuntu server 14.10
xvs: 1.6.11

**Comment by Jalle19** [comment]
You have to run the command from the correct directory, and you have to run everything as root like the instructions say. Can you post the complete error you're getting?

**Comment by Jalle19** [comment]
Any update on this?

**Comment by godfuture** [comment]
I have repeated the steps and still face issues. I think its possibly my setup or some misconfiguration, even I dont know where (mysql, php, yiic, file permissions).

When executing "yiic createinitialdatabase" from xbmc-video-server root, I get some permission error:
```
root@server:/var/www/xbmc-video-server# ./src/protected/yiic createinitialdatabase
bash: ./src/protected/yiic: Keine Berechtigung
```

Visiting the xbmc-video-server in browser just approve the problems with database:
```
CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kodi_server.t' doesn't exist
```
I have double checked the database, and the tables are not created. So I guess solving the permissions problem is the key to success :)

**Comment by godfuture** [comment]
I finally got it working. For anyone having the same trouble:
* I did not mark yiic as executable
* As I am using mysql, the createinitialdatabase script does not work, but (as noted in the config file main.php), importing the sql schema will help
* Make sure all files are proper accessable by apache

Thank you Jalle19, I appreciate your quick response. Unfortunately I was just another newbie, sorry for that!!!

**Comment by Jalle19** [comment]
The `yiic` script is executable by default, you shouldn't have to make it executable yourself. There is an issue that I encounter from time to time though if you use Samba to share the directory where your files are located. In that case Samba often overwrites the permissions set by the underlying filesystem which may remove the executable bit from the script. I've modified the installation instructions on the wiki to call `php ./src/protected/yiic.php` instead of just `./src/protected/yiic`, that way it doesn't matter if the file is executable or not.

I should probably add a small guide on how to use MySQL to the wiki, I've never used it myself for this application so I've never bothered.
